[smtp]
host = "smtp.gmail.com"
port = 587
use_ssl = false
user = "sean.chinery@gmail.com"
password = "hijr fbyu hpcm rmhh"   # ‚Üê 16 chars, NO SPACES
from = "sean.chinery@gmail.com" # must equal user for Gmail
force_from_user = true
to = "sean.chinery@atlantichealth.org"
